"""
Django settings for hyacinthwatch project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
from urllib.parse import urlparse, urlunparse, parse_qsl, urlencode

# Load environment variables
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / ".env"
DOCKER_ENV_PATH = BASE_DIR / ".env.docker"

# always load local .env
load_dotenv(ENV_PATH)

# optionally load docker env to override (guarded)
if os.environ.get("DJANGO_IN_DOCKER") == "1" or os.path.exists(DOCKER_ENV_PATH):
    load_dotenv(DOCKER_ENV_PATH, override=True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r1(_3#+6792j)$p((()#$^i7#-4w-06^pbjuo6zx=mxsa6&ile'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'rest_framework',
    'corsheaders',
    'storages',
    # local
    'observations',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow CRA dev server
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    # Allow local network dev host (add your machine IP when developing from another device)
    'http://10.74.82.53:3000',
]

# Allow cookies/credentials to be sent from the frontend when using
# credentialed requests (fetch credentials: 'include'). This ensures the
# Access-Control-Allow-Credentials header is set to 'true' in responses.
CORS_ALLOW_CREDENTIALS = True

# For quick local development you can also enable wildcard origins by setting
# the env var `CORS_ALLOW_ALL` to '1'. This is intentionally opt-in.
if os.environ.get('CORS_ALLOW_ALL') in ('1', 'true', 'True'):
    CORS_ALLOW_ALL_ORIGINS = True

# Dev‑only: open API
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

ROOT_URLCONF = 'hyacinthwatch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hyacinthwatch.wsgi.application'

# prefer a full DATABASE_URL when present (handles URL-encoded passwords)
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # dj-database-url returns a Django DATABASE dict
    # sanitize the URL: remove unsupported query params (e.g. pgbouncer)
    parsed = urlparse(DATABASE_URL)
    qs = dict(parse_qsl(parsed.query))
    qs.pop('pgbouncer', None)
    sanitized_query = urlencode(qs)
    sanitized = urlunparse(parsed._replace(query=sanitized_query))
    DATABASES = {'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=(
        os.environ.get('PGSSLMODE', '').lower() == 'require'))}
    DATABASES = {'default': dj_database_url.parse(sanitized, conn_max_age=600, ssl_require=(
        os.environ.get('PGSSLMODE', '').lower() == 'require'))}
    # ensure a short connect timeout so the process fails fast when network/DNS is flaky
    try:
        DATABASES['default'].setdefault('OPTIONS', {})
        DATABASES['default']['OPTIONS'].setdefault(
            'connect_timeout', int(os.environ.get('DB_CONNECT_TIMEOUT', 5)))
    except Exception:
        pass
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '6543'),
            'OPTIONS': {
                'sslmode': os.environ.get('PGSSLMODE', 'require'),
                # Fail fast when remote DB is unreachable (seconds)
                'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', 5)),
            },
        },
    }

# Small dev-friendly log so you can see which DB path was selected when starting
try:
    _db_info = DATABASES.get('default', {})
    print(
        f"[settings] Using DB engine={_db_info.get('ENGINE')} host={_db_info.get('HOST')} port={_db_info.get('PORT')}")
except Exception:
    pass


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Supabase / S3-compatible storage settings ---
# Use django-storages with an S3-compatible endpoint (Supabase Storage).
DEFAULT_FILE_STORAGE = os.environ.get(
    'DEFAULT_FILE_STORAGE', 'django.core.files.storage.FileSystemStorage')

if os.environ.get('USE_S3', '0') == '1':
    # switch on S3 backend when USE_S3=1
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', None)
    AWS_S3_ENDPOINT_URL = os.environ.get(
        'AWS_S3_ENDPOINT_URL') or os.environ.get('SUPABASE_URL')
    AWS_S3_ADDRESSING_STYLE = os.environ.get('AWS_S3_ADDRESSING_STYLE', 'path')
    AWS_DEFAULT_ACL = os.environ.get('AWS_DEFAULT_ACL', None)


# Celery connection resilience settings
# These are picked up by Celery when using ``app.config_from_object('django.conf:settings', namespace='CELERY')``
# and help workers tolerate transient broker restarts during local development.
CELERY_BROKER_CONNECTION_RETRY = True
# None => unlimited retries
CELERY_BROKER_CONNECTION_MAX_RETRIES = None
# Transport options passed to the Redis transport; visibility_timeout is useful
# for long-running tasks so Redis doesn't requeue too early.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': int(os.environ.get('CELERY_VISIBILITY_TIMEOUT', 3600))
}

# Orphaned-observation monitor configuration
# If an observation has no `pred.presence` after ORPHAN_PRESENCE_DELAY_MINUTES
# minutes, the periodic monitor will re-enqueue presence classification up
# to ORPHAN_PRESENCE_MAX_RETRIES times before giving up.
ORPHAN_PRESENCE_DELAY_MINUTES = int(
    os.environ.get('ORPHAN_PRESENCE_DELAY_MINUTES', '10'))
ORPHAN_PRESENCE_MAX_RETRIES = int(
    os.environ.get('ORPHAN_PRESENCE_MAX_RETRIES', '3'))


# Periodic Celery beat schedule: runs the orphan monitor every 5 minutes by default.
CELERY_BEAT_SCHEDULE = {
    'monitor-orphaned-observations': {
        'task': 'observations.monitor.retry_orphaned_presence',
        'schedule': timedelta(minutes=int(os.environ.get('ORPHAN_MONITOR_SCHEDULE_MINUTES', '5'))),
        'args': (),
    },
}
