# Generated by Django 4.2 on 2025-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='qc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='qc_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
