# Generated by Django 4.2 on 2025-10-20 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_add_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
