# Generated by Django 4.2 on 2025-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0004_alter_observation_captured_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="pred",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
