# Generated by Django 4.2 on 2025-10-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_add_pred_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deleted_mask_url', models.URLField(blank=True, null=True)),
                ('deleted_image_url', models.URLField(blank=True, null=True)),
                ('delete_remote', models.BooleanField(default=False)),
                ('remote_mask_deleted', models.BooleanField(null=True)),
                ('remote_image_deleted', models.BooleanField(null=True)),
                ('local_image_deleted', models.BooleanField(null=True)),
                ('db_updated', models.BooleanField(null=True)),
                ('actor', models.CharField(default='purge_task', max_length=128)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_logs', to='observations.observation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
