"""Add nullable user FK to Observation for gamification wiring.

Generated by hand to allow applying the DB change as part of wiring Observations to users.
"""
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_gamification'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
