# Generated by Django 4.2 on 2025-10-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_deletionlog'),
        ('observations', '0006_gamification'),
    ]

    operations = [
    ]
