# Generated by Django 4.2 on 2025-10-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_merge_0007_add_user_and_0007_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletionLog',
        ),
    ]
