# Minimal example config for segmentation training
data:
  train_dir: research/data/processed/train
  val_dir: research/data/processed/val
  img_size: [512, 512]
  batch_size: 4
  num_workers: 4

model:
  arch: unet
  encoder: resnet34
  pretrained: true

train:
  epochs: 10
  lr: 1e-3
  weight_decay: 1e-5
  degrade:
    jpeg_quality: [30, 90]   # robustness sweep range
    resize_min: 256          # min shorter-side for downscale

metrics:
  threshold: 0.5